version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  linux:
    docker:
      - image: crystallang/crystal:latest
    steps:
      - run:
          name: Install LLVM
          command: apt-get -q update; apt-get -y install llvm-8-dev
      - checkout
      - run:
          name: Build Crystal
          command: make
      - run:
          name: Write an example program
          command: echo 'puts "Hello world!"' > hello_world.cr
      - run:
          name: Cross-compile the program for Windows
          command: bin/crystal build --cross-compile -Dgc_none --target x86_64-pc-windows-msvc hello_world.cr
      - persist_to_workspace:
          root: .
          paths:
            - hello_world.o

  windows:
    executor: win/default
    steps:
      - run:
          name: Download CMake
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr https://cmake.org/files/v3.11/cmake-3.11.4-win64-x64.zip -OutFile cmake.zip
            Expand-Archive cmake.zip -DestinationPath .
            rm cmake.zip
      - run:
          name: Download PCRE
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr https://ftp.pcre.org/pub/pcre/pcre-8.42.zip -OutFile pcre.zip
            Expand-Archive pcre.zip -DestinationPath .
            rm pcre.zip
      - run:
          name: Build PCRE
          shell: cmd.exe
          command: |
            mkdir pcre-8.42\build
            cd pcre-8.42\build
            cmake-3.11.4-win64-x64\bin\cmake .. -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=OFF -DPCRE_SUPPORT_UNICODE_PROPERTIES=ON -DPCRE_SUPPORT_JIT=ON -DPCRE_STATIC_RUNTIME=ON | Out-Default
            cmake-3.11.4-win64-x64\bin\cmake --build . --config release | Out-Default
            mv release\pcre.lib ..\..\pcre.lib
            cd ..\..
      - run:
          name: Download libgc
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr https://github.com/ivmai/bdwgc/archive/v7.6.6.zip -OutFile bdwgc.zip
            Expand-Archive bdwgc.zip -DestinationPath .
            rm bdwgc.zip
      - run:
          name: Download libatomic_ops
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr https://github.com/ivmai/libatomic_ops/archive/v7.6.4.zip -OutFile libatomic_ops.zip
            Expand-Archive libatomic_ops.zip -DestinationPath .
            rm libatomic_ops.zip
            mv libatomic_ops-7.6.4 bdwgc-7.6.6\libatomic_ops
      - run:
          name: Download win32.mak
          command: |
            $ProgressPreference = "SilentlyContinue"
            iwr https://gist.github.com/ynkdir/688e62f419e5374347bf/raw/d250598ddf5129addd212b8390279a01bca12706/win32.mak -OutFile bdwgc-7.6.6\ntwin32.mak
      - run:
          name: Build libgc
          shell: cmd.exe
          command: |
            C:\Program^ Files^ ^(x86^)\Microsoft^ Visual^ Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat x64
            cd bdwgc-7.6.6
            nmake -f NT_X64_STATIC_THREADS_MAKEFILE nodebug=1 _CL_=-DDONT_USE_USER32_DLL
            mv gc.lib ..\gc.lib
            cd ..
      - attach_workspace:
          at: workspace
      - run:
          name: Link the executable
          shell: cmd.exe
          command: |
            C:\Program^ Files^ ^(x86^)\Microsoft^ Visual^ Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat x64
            cl.exe workspace\hello_world.o /Fehello_world pcre.lib gc.lib advapi32.lib libcmt.lib legacy_stdio_definitions.lib
      - run:
          name: Run the executable
          command: hello_world.exe

workflows:
  version: 2
  ci:
    jobs:
      - linux
      - windows:
          requires:
            - linux
